from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from .rag import RAGSystem
from typing import Dict

app = FastAPI(title="Chatbot API")
rag_system = RAGSystem()

class Query(BaseModel):
    text: str

class Response(BaseModel):
    response: str
    source: str
    response_time: float

@app.post("/chat", response_model=Response)
async def chat(query: Query) -> dict:
    """
    This endpoint receives a query and returns a response generated by the RAG system.

    Args:
        query: The user's query.

    Returns:
        A dictionary containing the response, the source of the response (cache or API), and the response time in seconds.

    Raises:
        HTTPException: If an error occurs during response generation.
    """
    try:
        result = rag_system.get_answer(query.text)
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating response: {str(e)}")

@app.get("/health")
async def health_check() -> dict:
    """
    This endpoint checks the health of the API.

    Returns:
        A dictionary indicating the status of the API.
    """
    return {"status": "healthy"}
